### ISSUE TITLE
getSensorData Route - areaModels for Tetrad

### ISSUE THREAD

**Issue by tbec** [aqandu/aqandu_live_site#46]
can't do areaModel parameters for Tetrad, because missing the `if "label" in db_headings"` clause

**Comment by rosswhitaker** [comment]
This has been fixed and tested for the area_params.json associated with slc_ut, clev_oh, etc.

**Comment by rosswhitaker** [comment]
> This has been fixed and tested for the area_params.json associated with slc_ut, clev_oh, etc.

And pushed up to the -regions branch.
